/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnimalCampaign {
  'id' : bigint,
  'title' : string,
  'endDate' : Time,
  'description' : string,
  'isActive' : boolean,
  'imageUrl' : string,
  'animalType' : string,
  'amountRaised' : bigint,
  'fundraisingGoal' : bigint,
  'startDate' : Time,
}
export interface Donation {
  'isRecurring' : boolean,
  'donorName' : string,
  'campaignId' : bigint,
  'referenceId' : string,
  'timestamp' : Time,
  'amount' : bigint,
  'donor' : Principal,
}
export interface DonorProfile {
  'nickname' : string,
  'recurringDonationAmount' : bigint,
  'mobileNumber' : string,
  'anonymous' : boolean,
  'imageUrl' : string,
  'totalDonated' : bigint,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelRecurringDonation' : ActorMethod<[], undefined>,
  'createCampaign' : ActorMethod<
    [string, string, string, string, bigint, Time, Time],
    bigint
  >,
  'deactivateCampaign' : ActorMethod<[bigint], undefined>,
  'getActiveCampaigns' : ActorMethod<[], Array<AnimalCampaign>>,
  'getAllCampaigns' : ActorMethod<[], Array<AnimalCampaign>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [DonorProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCampaign' : ActorMethod<[bigint], [] | [AnimalCampaign]>,
  'getDonationHistory' : ActorMethod<[], Array<Donation>>,
  'getRecurringDonations' : ActorMethod<[], Array<Donation>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [DonorProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[DonorProfile], undefined>,
  'submitDonation' : ActorMethod<[bigint, bigint], string>,
  'submitRecurringDonation' : ActorMethod<[bigint, bigint], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];