/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const AnimalCampaign = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'endDate' : Time,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'animalType' : IDL.Text,
  'amountRaised' : IDL.Nat,
  'fundraisingGoal' : IDL.Nat,
  'startDate' : Time,
});
export const DonorProfile = IDL.Record({
  'nickname' : IDL.Text,
  'recurringDonationAmount' : IDL.Nat,
  'mobileNumber' : IDL.Text,
  'anonymous' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'totalDonated' : IDL.Nat,
});
export const Donation = IDL.Record({
  'isRecurring' : IDL.Bool,
  'donorName' : IDL.Text,
  'campaignId' : IDL.Nat,
  'referenceId' : IDL.Text,
  'timestamp' : Time,
  'amount' : IDL.Nat,
  'donor' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelRecurringDonation' : IDL.Func([], [], []),
  'createCampaign' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, Time, Time],
      [IDL.Nat],
      [],
    ),
  'deactivateCampaign' : IDL.Func([IDL.Nat], [], []),
  'getActiveCampaigns' : IDL.Func([], [IDL.Vec(AnimalCampaign)], ['query']),
  'getAllCampaigns' : IDL.Func([], [IDL.Vec(AnimalCampaign)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(DonorProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCampaign' : IDL.Func([IDL.Nat], [IDL.Opt(AnimalCampaign)], ['query']),
  'getDonationHistory' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
  'getRecurringDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(DonorProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([DonorProfile], [], []),
  'submitDonation' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Text], []),
  'submitRecurringDonation' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const AnimalCampaign = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'endDate' : Time,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'animalType' : IDL.Text,
    'amountRaised' : IDL.Nat,
    'fundraisingGoal' : IDL.Nat,
    'startDate' : Time,
  });
  const DonorProfile = IDL.Record({
    'nickname' : IDL.Text,
    'recurringDonationAmount' : IDL.Nat,
    'mobileNumber' : IDL.Text,
    'anonymous' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'totalDonated' : IDL.Nat,
  });
  const Donation = IDL.Record({
    'isRecurring' : IDL.Bool,
    'donorName' : IDL.Text,
    'campaignId' : IDL.Nat,
    'referenceId' : IDL.Text,
    'timestamp' : Time,
    'amount' : IDL.Nat,
    'donor' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelRecurringDonation' : IDL.Func([], [], []),
    'createCampaign' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, Time, Time],
        [IDL.Nat],
        [],
      ),
    'deactivateCampaign' : IDL.Func([IDL.Nat], [], []),
    'getActiveCampaigns' : IDL.Func([], [IDL.Vec(AnimalCampaign)], ['query']),
    'getAllCampaigns' : IDL.Func([], [IDL.Vec(AnimalCampaign)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(DonorProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCampaign' : IDL.Func([IDL.Nat], [IDL.Opt(AnimalCampaign)], ['query']),
    'getDonationHistory' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
    'getRecurringDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(DonorProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([DonorProfile], [], []),
    'submitDonation' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Text], []),
    'submitRecurringDonation' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };